# ESTAGIOS
stages:
  - Lint
  - Teste exceções
  - Teste paralelo_1
  - Teste paralelo_2

#Modelo
.Anchors: &config
    before_script:
      - export LANG="pt_BR.UTF-8" 
      - npm ci
    image: cypress/browsers:node16.14.2-slim-chrome103-ff102
    variables:
      TEST_ENV: CI
      BASE_URL_FRONT: "http://"
    artifacts:
      when: on_failure
      expire_in: 1 week
      paths:
        - cypress/screenshots
        - cypress/videos
        - cypress/allure_results
    allow_failure: true
    only:
      - main
      - tags
      - merge_requests

# ESLINT
Eslint:
  stage: Lint
  image: node:12-alpine
  allow_failure: true
  script:
    - rm -rf node_modules package-lock.json
    - npm install
    - npm install eslint-plugin-mocha@latest --save-dev
    - npm run lint
  only:
    - main
    - tags
    - merge_requests

teste-1:
  stage: Teste exceções
  <<: *config
  script:
    - ./report.sh comando-execução-3

teste-2:
  stage: Teste paralelo_1
  <<: *config
  script:
    - ./report.sh comando-execução-2

teste-3:
  stage: Teste paralelo_1
  <<: *config
  script:
    - ./report.sh comando-execução-4
